### ISSUE TITLE
Error in if (any(select)) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by csqsiew** [SachaEpskamp/lvnet#1]
> library("lvnet")
> library("psych")
> library("lavaan")
> data(HolzingerSwineford1939)
> Data <- HolzingerSwineford1939[,7:15]
> Lambda <- matrix(0, 9, 3)
> Lambda[1:3,1] <- NA
> Lambda[4:6,2] <- NA
> Lambda[7:9,3] <- NA
> CFA <- lvnet(Data, lambda = Lambda)
**Error in if (any(select)) { : missing value where TRUE/FALSE needed**

Was simply trying to work through the example on the readme but had the following error pop up.

**Comment by SachaEpskamp** [comment]
Hi,

What version of R, lvnet and OpenMx are you using?

Best, Sacha

**Comment by csqsiew** [comment]
I have tried it on both machines, with the same error.

MacOS 10.12.6 (Sierra)
R 3.4.1 (Single Candle)
Rstudio 1.0.153
lvnet 0.3.2
OpenMX 2.7.10

Windows 7
R 3.4.2 (Short Summer)
Rstudio 1.0.153
lvnet 0.3.2
OpenMX 2.7.17

**Comment by SachaEpskamp** [comment]
I replicated the bug using the latest version of OpenMx. Working on it!

**Comment by csqsiew** [comment]
Thanks! Looking forward to the bug being fixed.

**Comment by SachaEpskamp** [comment]
Hi, I can no longer replicate the bug with OpenMx version 2.7.18. Do you still get it?

Best, Sacha

**Comment by csqsiew** [comment]
I am still getting the same error, even after updating to the latest version of OpenMx 2.7.18...

**Comment by csqsiew** [comment]
Hi Sacha,

Any updates? Would like to start analyzing some data that I have for a
project.

Cynthia

**Comment by SachaEpskamp** [comment]
Sorry for the late reply... this example works for me now, so I will close it for now. I am also moving all functionality to psychetrics (http://psychonetrics.org/), which may probably better suit your needs.
